### ISSUE TITLE
Hacktoberfest welcome

### ISSUE THREAD

**Issue by flarewitness** [anonshubh/issue-reporter#1]
1)One can Upgrade Styling in static/styles.css
2)One can Improve the Content in Index Page
3)One can Add required Models to Polling App

**Comment by anurawat01** [comment]
Hey, @anonshubh I would like to work on this? Will you please assign it to me?

**Comment by flarewitness** [comment]
Yes sure, would you like to help in Front-end(1 or 2) or Back-end(3), (for Back-end requisites required is basic knowledge of Django)

**Comment by sanskritinegi** [comment]
hi i would like to contribute

**Comment by anurawat01** [comment]
Hi, @anonshubh I will be more comfortable in Front-end?

**Comment by flarewitness** [comment]
@anurawat01 , You can Improve the Login/Signin buttons in Nav Bar(when user is not logged in)

**Comment by flarewitness** [comment]
@sanskritinegi , You can Improve the Fonts Family in the App

**Comment by marcodeanda** [comment]
Hey! I would like to help with the front end, let me know what task I can do, thanks!
